# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Freiburg Galaxy
email: galaxy@uni-freiburg.de
description: > # this means to ignore newlines until "baseurl:"
    The Freiburg Galaxy Team offers a framework for scientists on e.g. NGS
    data analyses (RNA-seq, ChIP-seq, Exome-seq, MethylC-seq), genome
    annotation analyses for eukaryotic and prokaryotic organisms (from gene
    prediction to functional description), Proteomics and Metabolomics
    analysis, and the ChemicalToolBoX for analysis of small compounds.
    Furthermore, Galaxy has a huge variety of data visualization tools. Galaxy
    contains more than 800 different single analysis tools and ready-to-use
    pipelines for different applications. After registration, all tools and
    the infrastructure for data analysis are freely available and can be used
    for creation of your own workflows for your specific projects. 
baseurl: "/galaxy-freiburg" # the subpath of your site, e.g. /blog
url: "https://backofenlab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: backofenlab
github_username:  backofenlab

# Build settings
markdown: kramdown
#theme: minima
plugins:
  - jekyll-feed
  #- jekyll/scholar

scholar:
  style: bioinformatics
  group_by: year

citation:
    citation_style: apa
    citation_locale: en

header_links:
    - name: News
      url: /news/
    - name: Events
      url: /events/
    - name: People
      url: /people/
    - name: Services
      url: /services/
    - name: Publications
      url: /publications/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#
# This will simultaneously render all collection items as "plain" pages
collections:
  collection_plain:
    permalink: /posts/:path/plain.html
    output: true

defaults:
  -
    scope:
      path: "_collection_plain"
    values:
      layout: default-galaxy
